### ISSUE TITLE
Missing comma in /src/parseError.js line 25

### ISSUE THREAD

**Issue by UserMcUser** [artemis-nerds/node-asbs-lib#14]
In parseError.js, there is a comma missing from the end of line 25.

**Comment by mrfishie** [comment]
Thanks! Interesting that this passed through unnoticed until now...

**Comment by mrfishie** [comment]
This seems to originate from https://github.com/artemis-nerds/node-asbs-lib/commit/3012e065624bbbeeaebe448e112ba2ce37cd1201. Perhaps we should add some tests with JSLint/Hint, @IvanSanchez?

**Comment by IvanSanchez** [comment]
@mrfishie Given that I set up a Gobble build system for this, maybe the best approach is https://www.npmjs.com/package/gobble-eslint

**Comment by IvanSanchez** [comment]
@mrfishie Have a look at the `gobble-eslint` branch. Apparently eslint doesn't quite work well with ES6 code still.
Also, Babeljs picks up this error - I wonder why we didn't see this before, given that running `npm run-script watch` is quite a requirement when developing this.

**Comment by mrfishie** [comment]
@IvanSanchez Perhaps we could set up a CI task to run Babeljs and detect errors..

**Comment by IvanSanchez** [comment]
If you know how to set Travis (I don't), please go for it!
