### ISSUE TITLE
Branching for 2.2.0?

### ISSUE THREAD

**Issue by UserMcUser** [artemis-nerds/node-asbs-lib#16]
Shouldn't the 2.1.5 code be forked into a new branch before the 2.2.0 changes go into the master?

Per the "CONTRIBUTING.md" doc:
"One of the aims of this library is to try and have compatibility with different versions of Artemis SBS. The master branch shall host the code compatible with the latest available version of the game. Branches compatible with previous versions shall be hosted in branches with the version supported, e.g. artemis-v2.1.0"

**Comment by TheWrongAlice** [comment]
Sounds reasonable.
Hi btw I'm new around here :)

**Comment by TheWrongAlice** [comment]
Or we could just tag the master branch at a commit that is stable for 2.1.5 (release feature in github)

**Comment by IvanSanchez** [comment]
@TheWrongAlice Keep in mind that a tag is not a branch. Branches allow for backporting bugfixes if really needed, tags do not.

**Comment by TheWrongAlice** [comment]
Well, except you can always create a branch out of a tag

**Comment by rjwut** [comment]
Side note: I am considering the possibility of making one version of ArtClientLib able to support multiple versions of Artemis. (rjwut/ArtClientLib#55) There are obviously certain issues with this undertaking which I am trying to figure out to determine whether it makes sense or not. Information that results from this may (or may not) turn out to be useful to this conversation here, so I wanted to call it to your attention and invite your comments.
