### ISSUE TITLE
Error behaviour

### ISSUE THREAD

**Issue by IvanSanchez** [artemis-nerds/node-asbs-lib#5]
As @mrfishie says:

> In artemis-protocol instead of calling _debugBuffer I provided the buffer as part of the error object, which makes more sense in my opinion. It allows the application to do something else with the buffer data other than just output it (for example, the parent application might want to log to a file, or do something else). Also, from what I can tell, its generally good practice to disconnect the client from the server if a parse error occurs (and for not-so-bad errors you might then want to do something else than trigger the 'error' event, as that event throws the error if it isn't handled).

**Comment by IvanSanchez** [comment]
I'm not sure on how the API for this should look like.

The rationale behind `_debugBuffer` is seeing the raw packet to debug the protocol. And, in that case, I want the library to keep going - usually unparseable packets appear several times in a row, and seeing several of them together in the console makes sense. I don't think it's a good idea to disconnect, specially when the code is able to skip the packet as it knows how long it is.

I'm ambivalent about passing the `Buffer` as part of a parse error. I just don't see any workflow / use case for it right now.

Maybe we can panic and disconnect on serious errors (bad magic number / header) and keep going on on parse errors. Maybe the library shouldn't emit `error` but `unparsed` or something like that.

**Comment by mrfishie** [comment]
Yeah, thats pretty much what I was thinking. 'Critical' errors like bad magic number, header, etc could go through the `error` event, which could then have a handler that closes the connection. 'Not-so-critical' errors could go through another event (e.g. `warn`) that doesn't close the connection, and allows the parent application to behave differently depending on the type of the event.
This is how I would implement it: https://github.com/mrfishie/node-artemis-lib/blob/master/src/artemisSocket.js

**Comment by IvanSanchez** [comment]
That code looks quite good to me. :+1:  Can you please make a pull request? And check line 103 BTW.

I'd change `warn` into either `unparsed` or `parseError` or `skip`, though.

**Comment by mrfishie** [comment]
Yeah, I wasn't exactly sure what we would want to do for a parse error.. should we continue with the remains or panic?

**Comment by IvanSanchez** [comment]
In case of a parse error, fire an event with a `ParseError`, stop parsing the current packet and skip to the next. This way, the library will wait until the next artemis packet (starting with the `0xdeadbeef` magic) and keep working.

This just means calling `return this._parseData( remainingBuffer );` after parse errors, exactly as it does now in most cases.

Maybe we should switch the logic in order to implement a packet queue and depend on `setImmediate()` timers for parsing each one or something. This means parsing the header and the payload would be splitted into two separate functions.

**Comment by mrfishie** [comment]
Should we close the socket (i.e trigger `error`) after a parse error occurs, or finish parsing the current buffer and then exit? The packet queue sounds interesting.. what would the advantages be by parsing each packet with `setImmediate()`?

**Comment by IvanSanchez** [comment]
> what would the advantages be by parsing each packet with `setImmediate()`?

None, API-wise. It's just reorganising code around a bit.

After giving this a bit of thought, maybe using the internal event queue is better. Have `_parseData` just concatenate and split a receving buffer, then emit a `rawPacket` event, passing the packet payload inside a `Buffer` instance (i.e. `buffer.slice(0, initialPointer + header.packetLength)`). This step is the one in which `error` events are possible.

Then, have `_onRawPacket()` parse packet type/subtype, and unpack the data. This is where the `packet` and `unparsed` events are emitted from.
