### ISSUE TITLE
Implement boolean datatypes

### ISSUE THREAD

**Issue by IvanSanchez** [artemis-nerds/node-asbs-lib#6]
Quite a lot of packet fields are integers but can have values of 0 and 1 (red alert, shields up, third person perspective, paused, etc).

Implement `bool8`, `bool16` and `bool32` boolean datatypes for this. Just like the `int8`, `int16` and `int32` datatypes, but casting from/to boolean when packing/unpacking.

**Comment by rjwut** [comment]
I agree that the datatypes described here would be useful, but I would be cautious about using boolean for all of these cases, as it may not be future-proof. For example, if Thom eventually introduces other alert states besides just normal and red, you'll have to change your boolean to something else. Refactoring is not the end of the world, but you will want to try to make your API as future-proof as possible to minimize breaking changes.

**Comment by IvanSanchez** [comment]
Yeah, but protocol changes means the code using this library will have to adapt.

And this being javascript (with its impressively loose typing) everything can be type-casted into _truthy_ or _falsey_, so I don't expect any real problems.

I just want to see pretty-printed `true` and `false` values when printing parsed payloads.

**Comment by mrfishie** [comment]
A agree with Robert.. One of the goals of node-artemis-lib, according to the readme, is to

> allow programs and scripts to switch the version of `node-artemis-lib` for newer versions of ArtemisSBS and **still work seamlessly even when the protocol changes**.

This is one of the reasons I wanted to implement enums: the client gets a nice, readable value, and values can be normalized across versions: if all the values are offset by 1, for example, in a future update, the parent code doesn't have to change.

In this case, I think that returning `enabled` or `disabled` (or similar) for all current boolean types, and then if a packet adds a value that is not 0 or 1, create an enum specifically for that with `enabled`, `disabled`, and the added value.

If an application wants to check if the value is enabled, it can test `value !== 'disabled'`. If it wants to check if the value is _only_ enabled (and not whatever other state is added), it can test `value === 'enabled'`.

That way, you get the best of both worlds: pretty-printed values, and a future-proof API.

**Comment by IvanSanchez** [comment]
You can think of a `Bool` of an enum which maps 0 to `false, 1 to`true` and if the protocol changes, we can squeeze more enum values there.

But I fear that'd make the code worthy of The Daily WTF :-/ http://thedailywtf.com/articles/What_Is_Truth_0x3f_

I don't really know what to do. Should it be safer to just keep returning `int`s for the time being?

**Comment by mrfishie** [comment]
If the property is a boolean, people will do checks like:

``` js
if (prop) { /* do something */ }
else { /* do something else */ }
```

This means that if another value is added to the enum, it will match with the `if (prop)` check, which could break things for the application. Instead, by mapping 1 and 0 to values depending on the property type, you don't end up with the Daily WTF thing, and code makes more sense..

For example, if you had a red alert property that originally used a boolean enum and then had a 'yellow' alert added, to find which alert it is you would need something like this:

``` js
if (alert === true) console.log('its a red alert'); // what??!
else if (alert === 'yellow') console.log('its a yellow alert');
else console.log('no alert');
```

If you instead originally mapped the property to the enum `red` and `disabled`, people wouldn't be able to do something like this:

``` js
if (alert) console.log('red alert enabled');
else console.log('no alert');
```

(which would probably break if a new alert level was added)

While also making sure the code makes sense:

``` js
if (alert === 'red') console.log('its a red alert');
else if (alert === 'yellow') console.log('its a yellow alert');
else console.log('no alert');
```

This means that code remains readable and always makes sense if a new level is added, while also making sure that the user of the library is cautious about new levels being added, by forcing them to check the actual value of the property. It also means that if the values are offset (i.e yellow alert becomes `1` and red alert becomes `2`), the developer of the application won't have to look through everywhere that the property is used and offset it by 1.

Of course, there are still some things where the value is almost definitely not going to change (e.g. console selected) where a boolean could be used.

**Comment by IvanSanchez** [comment]
> if you had a red alert property

... then it'd be named `redalert`: 

``` javascript
if (foo.redAlert) console.log('red alert enabled');
else console.log('no red alert');
```

And if a posterior version of Artemis implements yellow, then the code would decorate the data with a synthetic property during unpacking, like:

``` javascript
if (justUnpacked.alert === 'red') { // assuming 'alert' is an enum
   justUnpacked.redAlert = true;
   justUnpacked.yellowAlert = false;
} else if (justUnpacked.alert === 'yellow') {
   justUnpacked.redAlert = false;
   justUnpacked.yellowAlert = true;
}}
```

**Comment by mrfishie** [comment]
Since we can't have two alert states at once, wouldn't it make more sense to hold the state in a single variable? In my opinion, libraries like this should be designed so that the user is aware that things could change in the future - in this case by requiring them to compare a string, avoiding Javascripts type casting in potentially dangerous cases.

**Comment by IvanSanchez** [comment]
> wouldn't it make more sense to hold the state in a single variable?

Depends on the semantics of the fields, and the degree of backwards compatibility we want to have in the library.
